"""empty message

Revision ID: de69e8ded068
Revises: 631c4cba3a01
Create Date: 2026-04-20 18:02:37.584331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de69e8ded068'
down_revision = '631c4cba3a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media')
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.drop_column('id')

    op.create_table('media',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='media_post_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='media_pkey')
    )
    # ### end Alembic commands ###
